apiVersion: v1
kind: Pod
metadata:
  name: wyse-blocker
spec:
  nodeName: dgoh-wyze
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10
    resources:
      requests:
        cpu: "2000m" #2CPU cores
        memory: "2Gi"  #2GB RAM
