apiVersion: v1
kind: Pod
metadata:
  name: wyse-blocker
spec:
  nodeName: wyse
  containers:
  - name: pause
    image: registry.k8s.io/pause:3.10
    resources:
      requests:
        cpu: "3000m" #3 CPU Kerne
