apiVersion: v1
kind: Pod
metadata:
  name: bench-train-cpu
spec:
  restartPolicy: Never
  nodeName: "tvpc"
  containers:
  - name: task
    image: 192.168.188.23:5000/benchmark-cpu-standard:v1
    env:
    - name: NODE_NAME
      value: "tvpc"
    - name: MATRIX_SIZE
      value: "4096"
    - name: NUM_ITERATIONS
      value: "50"
